schema_version = "1.0.33"

id = "blendercam"
version = "1.0.33"
name = "BlenderCAM"
tagline = "G-code Generation Tools"
maintainer = "Alain Pelletier and Contributors"
type = "add-on"

website = "https://blendercam.com/"

tags = ["3D View", "Add Curve", "Add Mesh", "Import-Export", "Object"]

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]

copyright = [
  "2012-2024 Vilem Novak, Alain Pelletier",
]

wheels = [
    # opencamlib
  "./wheels/opencamlib-2023.1.11-cp311-cp311-macosx_10_9_x86_64.whl",
  "./wheels/opencamlib-2023.1.11-cp311-cp311-macosx_11_0_arm64.whl",
  "./wheels/opencamlib-2023.1.11-cp311-cp311-manylinux_2_17_aarch64.manylinux2014_aarch64.whl",
  "./wheels/opencamlib-2023.1.11-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
  "./wheels/opencamlib-2023.1.11-cp311-cp311-win_amd64.whl",
  "./wheels/opencamlib-2023.1.11-cp311-cp311-win32.whl",

    # shapely
  "./wheels/shapely-2.0.5-cp311-cp311-macosx_10_9_x86_64.whl",
  "./wheels/shapely-2.0.5-cp311-cp311-macosx_11_0_arm64.whl",
  "./wheels/shapely-2.0.5-cp311-cp311-manylinux_2_17_aarch64.manylinux2014_aarch64.whl",
  "./wheels/shapely-2.0.5-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
  "./wheels/shapely-2.0.5-cp311-cp311-win_amd64.whl",
  "./wheels/shapely-2.0.5-cp311-cp311-win32.whl",
]

[permissions]
files = "Import/export G-code files from/to disk"

# Optional: build settings.
# https://docs.blender.org/manual/en/dev/advanced/extensions/command_line_arguments.html#command-line-args-extension-build
# [build]
# paths_exclude_pattern = [
#   "__pycache__/",
#   "/.git/",
#   "/*.zip",
# ]
